/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IControllerInterface extends ethers.utils.Interface {
  functions: {
    "basePrice(string)": FunctionFragment;
    "getPrices()": FunctionFragment;
    "getTokenPrice()": FunctionFragment;
    "nameRedeem(string,address,uint64,uint256,bytes)": FunctionFragment;
    "nameRegister(string,address,uint64)": FunctionFragment;
    "nameRegisterByManager(string,address,uint64,uint256,uint256[],string[])": FunctionFragment;
    "nameRegisterWithConfig(string,address,uint64,uint256,uint256[],string[])": FunctionFragment;
    "renew(string,uint64)": FunctionFragment;
    "renewByManager(string,uint64)": FunctionFragment;
    "renewPrice(string,uint64)": FunctionFragment;
    "rentPrice(string,uint64)": FunctionFragment;
    "setPrices(uint256[],uint256[])": FunctionFragment;
    "totalRegisterPrice(string,uint64)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "basePrice", values: [string]): string;
  encodeFunctionData(functionFragment: "getPrices", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTokenPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nameRedeem",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nameRegister",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nameRegisterByManager",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      string[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nameRegisterWithConfig",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      string[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renew",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renewByManager",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renewPrice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rentPrice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrices",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRegisterPrice",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "basePrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPrices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nameRedeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nameRegister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nameRegisterByManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nameRegisterWithConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "renew", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renewByManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "renewPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rentPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPrices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalRegisterPrice",
    data: BytesLike
  ): Result;

  events: {
    "CapacityUpdated(uint256,uint256)": EventFragment;
    "ConfigUpdated(uint256)": EventFragment;
    "NameRegistered(address,uint256,uint256,uint256,string)": EventFragment;
    "NameRenewed(uint256,uint256,uint256,string)": EventFragment;
    "PriceChanged(uint256[],uint256[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CapacityUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConfigUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NameRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NameRenewed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PriceChanged"): EventFragment;
}

export type CapacityUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber] & { tokenId: BigNumber; capacity: BigNumber }
>;

export type ConfigUpdatedEvent = TypedEvent<[BigNumber] & { flags: BigNumber }>;

export type NameRegisteredEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, string] & {
    to: string;
    node: BigNumber;
    cost: BigNumber;
    expires: BigNumber;
    name: string;
  }
>;

export type NameRenewedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, string] & {
    node: BigNumber;
    cost: BigNumber;
    expires: BigNumber;
    name: string;
  }
>;

export type PriceChangedEvent = TypedEvent<
  [BigNumber[], BigNumber[]] & {
    basePrices: BigNumber[];
    rentPrices: BigNumber[];
  }
>;

export class IController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IControllerInterface;

  functions: {
    basePrice(name: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getPrices(overrides?: CallOverrides): Promise<[BigNumber[], BigNumber[]]>;

    getTokenPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    nameRedeem(
      name: string,
      owner: string,
      duration: BigNumberish,
      deadline: BigNumberish,
      code: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    nameRegister(
      name: string,
      owner: string,
      duration: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    nameRegisterByManager(
      name: string,
      owner: string,
      duration: BigNumberish,
      data: BigNumberish,
      keyHashes: BigNumberish[],
      values: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    nameRegisterWithConfig(
      name: string,
      owner: string,
      duration: BigNumberish,
      data: BigNumberish,
      keyHashes: BigNumberish[],
      values: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renew(
      name: string,
      duration: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renewByManager(
      name: string,
      duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renewPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    rentPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setPrices(
      basePrices: BigNumberish[],
      rentPrices: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalRegisterPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  basePrice(name: string, overrides?: CallOverrides): Promise<BigNumber>;

  getPrices(overrides?: CallOverrides): Promise<[BigNumber[], BigNumber[]]>;

  getTokenPrice(overrides?: CallOverrides): Promise<BigNumber>;

  nameRedeem(
    name: string,
    owner: string,
    duration: BigNumberish,
    deadline: BigNumberish,
    code: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  nameRegister(
    name: string,
    owner: string,
    duration: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  nameRegisterByManager(
    name: string,
    owner: string,
    duration: BigNumberish,
    data: BigNumberish,
    keyHashes: BigNumberish[],
    values: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  nameRegisterWithConfig(
    name: string,
    owner: string,
    duration: BigNumberish,
    data: BigNumberish,
    keyHashes: BigNumberish[],
    values: string[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renew(
    name: string,
    duration: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renewByManager(
    name: string,
    duration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renewPrice(
    name: string,
    duration: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  rentPrice(
    name: string,
    duration: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setPrices(
    basePrices: BigNumberish[],
    rentPrices: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalRegisterPrice(
    name: string,
    duration: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    basePrice(name: string, overrides?: CallOverrides): Promise<BigNumber>;

    getPrices(overrides?: CallOverrides): Promise<[BigNumber[], BigNumber[]]>;

    getTokenPrice(overrides?: CallOverrides): Promise<BigNumber>;

    nameRedeem(
      name: string,
      owner: string,
      duration: BigNumberish,
      deadline: BigNumberish,
      code: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nameRegister(
      name: string,
      owner: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nameRegisterByManager(
      name: string,
      owner: string,
      duration: BigNumberish,
      data: BigNumberish,
      keyHashes: BigNumberish[],
      values: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nameRegisterWithConfig(
      name: string,
      owner: string,
      duration: BigNumberish,
      data: BigNumberish,
      keyHashes: BigNumberish[],
      values: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renew(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renewByManager(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renewPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rentPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setPrices(
      basePrices: BigNumberish[],
      rentPrices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    totalRegisterPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "CapacityUpdated(uint256,uint256)"(
      tokenId?: null,
      capacity?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { tokenId: BigNumber; capacity: BigNumber }
    >;

    CapacityUpdated(
      tokenId?: null,
      capacity?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { tokenId: BigNumber; capacity: BigNumber }
    >;

    "ConfigUpdated(uint256)"(
      flags?: null
    ): TypedEventFilter<[BigNumber], { flags: BigNumber }>;

    ConfigUpdated(
      flags?: null
    ): TypedEventFilter<[BigNumber], { flags: BigNumber }>;

    "NameRegistered(address,uint256,uint256,uint256,string)"(
      to?: null,
      node?: null,
      cost?: null,
      expires?: null,
      name?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, string],
      {
        to: string;
        node: BigNumber;
        cost: BigNumber;
        expires: BigNumber;
        name: string;
      }
    >;

    NameRegistered(
      to?: null,
      node?: null,
      cost?: null,
      expires?: null,
      name?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber, string],
      {
        to: string;
        node: BigNumber;
        cost: BigNumber;
        expires: BigNumber;
        name: string;
      }
    >;

    "NameRenewed(uint256,uint256,uint256,string)"(
      node?: null,
      cost?: null,
      expires?: null,
      name?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, string],
      { node: BigNumber; cost: BigNumber; expires: BigNumber; name: string }
    >;

    NameRenewed(
      node?: null,
      cost?: null,
      expires?: null,
      name?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, BigNumber, string],
      { node: BigNumber; cost: BigNumber; expires: BigNumber; name: string }
    >;

    "PriceChanged(uint256[],uint256[])"(
      basePrices?: null,
      rentPrices?: null
    ): TypedEventFilter<
      [BigNumber[], BigNumber[]],
      { basePrices: BigNumber[]; rentPrices: BigNumber[] }
    >;

    PriceChanged(
      basePrices?: null,
      rentPrices?: null
    ): TypedEventFilter<
      [BigNumber[], BigNumber[]],
      { basePrices: BigNumber[]; rentPrices: BigNumber[] }
    >;
  };

  estimateGas: {
    basePrice(name: string, overrides?: CallOverrides): Promise<BigNumber>;

    getPrices(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenPrice(overrides?: CallOverrides): Promise<BigNumber>;

    nameRedeem(
      name: string,
      owner: string,
      duration: BigNumberish,
      deadline: BigNumberish,
      code: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    nameRegister(
      name: string,
      owner: string,
      duration: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    nameRegisterByManager(
      name: string,
      owner: string,
      duration: BigNumberish,
      data: BigNumberish,
      keyHashes: BigNumberish[],
      values: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    nameRegisterWithConfig(
      name: string,
      owner: string,
      duration: BigNumberish,
      data: BigNumberish,
      keyHashes: BigNumberish[],
      values: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renew(
      name: string,
      duration: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renewByManager(
      name: string,
      duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renewPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rentPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setPrices(
      basePrices: BigNumberish[],
      rentPrices: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalRegisterPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    basePrice(
      name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrices(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTokenPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nameRedeem(
      name: string,
      owner: string,
      duration: BigNumberish,
      deadline: BigNumberish,
      code: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    nameRegister(
      name: string,
      owner: string,
      duration: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    nameRegisterByManager(
      name: string,
      owner: string,
      duration: BigNumberish,
      data: BigNumberish,
      keyHashes: BigNumberish[],
      values: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    nameRegisterWithConfig(
      name: string,
      owner: string,
      duration: BigNumberish,
      data: BigNumberish,
      keyHashes: BigNumberish[],
      values: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renew(
      name: string,
      duration: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renewByManager(
      name: string,
      duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renewPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rentPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setPrices(
      basePrices: BigNumberish[],
      rentPrices: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalRegisterPrice(
      name: string,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
