/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOwnable } from "./IOwnable";
export type { IPNS } from "./IPNS";
export type { IController } from "./IController";
export type { IResolver } from "./IResolver";

export { IOwnable__factory } from "./factories/IOwnable__factory";
export { IPNS__factory } from "./factories/IPNS__factory";
export { IController__factory } from "./factories/IController__factory";
export { IResolver__factory } from "./factories/IResolver__factory";
