/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { EchidnaHelper, EchidnaHelperInterface } from "../EchidnaHelper";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "AssertionFailed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "m",
        type: "string",
      },
    ],
    name: "Debug",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220faf3303b7b245b87083833d795e0656a17102c9b3cc4cc8ea7a7de3dcbd5f55f64736f6c63430008090033";

export class EchidnaHelper__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<EchidnaHelper> {
    return super.deploy(overrides || {}) as Promise<EchidnaHelper>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): EchidnaHelper {
    return super.attach(address) as EchidnaHelper;
  }
  connect(signer: Signer): EchidnaHelper__factory {
    return super.connect(signer) as EchidnaHelper__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EchidnaHelperInterface {
    return new utils.Interface(_abi) as EchidnaHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EchidnaHelper {
    return new Contract(address, _abi, signerOrProvider) as EchidnaHelper;
  }
}
