/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ERC2771ContextUpgradeableNoGap,
  ERC2771ContextUpgradeableNoGapInterface,
} from "../ERC2771ContextUpgradeableNoGap";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ERC2771ContextUpgradeableNoGap__factory {
  static readonly abi = _abi;
  static createInterface(): ERC2771ContextUpgradeableNoGapInterface {
    return new utils.Interface(_abi) as ERC2771ContextUpgradeableNoGapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC2771ContextUpgradeableNoGap {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC2771ContextUpgradeableNoGap;
  }
}
